apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: ecommerce
spec:
  selector:
    app: payment

  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005

  type: ClusterIP