apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: catalogue

  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

  type: ClusterIP