apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment

    spec:
      containers:
        - name: payment
          image: "{{ .Values.images.payment.repository }}:{{ .Values.images.payment.tag }}"

          ports:
            - containerPort: 3005

          env:
            - name: ORDERS_URL
              value: "http://orders:3004"

            - name: NOTIFICATIONS_URL
              value: "http://notifications:3006"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 20
            periodSeconds: 20